# Generated by Django 5.1.15 on 2026-02-17 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('ad_group_dn', models.TextField(blank=True, default='', help_text='Distinguished name of the AD group mapped to this role.')),
                ('description', models.TextField(blank=True, default='')),
                ('priority', models.IntegerField(default=0, help_text='Higher value = more privileges.')),
            ],
            options={
                'ordering': ['-priority'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_dn', models.TextField(blank=True, default='', help_text='AD Distinguished Name')),
                ('ad_guid', models.CharField(blank=True, default='', help_text='AD objectGUID', max_length=36)),
                ('last_synced', models.DateTimeField(auto_now=True)),
                ('roles', models.ManyToManyField(blank=True, to='accounts.role')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__username'],
            },
        ),
    ]
