# Generated by Django 5.1.15 on 2026-02-17 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='ad_guid',
            field=models.CharField(blank=True, default='', help_text='AD objectGUID', max_length=64),
        ),
    ]
