"""Application-wide constants."""

# Role names
ROLE_ADMIN = 'Admin'
ROLE_HELPDESK = 'HelpDesk'
ROLE_GROUP_MANAGER = 'GroupManager'
ROLE_READONLY = 'ReadOnly'

ALL_ROLES = [ROLE_ADMIN, ROLE_HELPDESK, ROLE_GROUP_MANAGER, ROLE_READONLY]

# Role hierarchy (higher index = more privileges)
ROLE_HIERARCHY = {
    ROLE_READONLY: 0,
    ROLE_GROUP_MANAGER: 1,
    ROLE_HELPDESK: 2,
    ROLE_ADMIN: 3,
}

# Audit action categories
AUDIT_CATEGORY_AUTH = 'authentication'
AUDIT_CATEGORY_USER = 'user_management'
AUDIT_CATEGORY_GROUP = 'group_management'
AUDIT_CATEGORY_DNS = 'dns_management'
AUDIT_CATEGORY_GPO = 'gpo'
AUDIT_CATEGORY_NOTIFICATION = 'notification'
AUDIT_CATEGORY_ADMIN = 'admin'

# AD User Account Control flags
UAC_FLAGS = {
    0x0001: 'SCRIPT',
    0x0002: 'ACCOUNTDISABLE',
    0x0008: 'HOMEDIR_REQUIRED',
    0x0010: 'LOCKOUT',
    0x0020: 'PASSWD_NOTREQD',
    0x0040: 'PASSWD_CANT_CHANGE',
    0x0080: 'ENCRYPTED_TEXT_PWD_ALLOWED',
    0x0100: 'TEMP_DUPLICATE_ACCOUNT',
    0x0200: 'NORMAL_ACCOUNT',
    0x0800: 'INTERDOMAIN_TRUST_ACCOUNT',
    0x1000: 'WORKSTATION_TRUST_ACCOUNT',
    0x2000: 'SERVER_TRUST_ACCOUNT',
    0x10000: 'DONT_EXPIRE_PASSWORD',
    0x20000: 'MNS_LOGON_ACCOUNT',
    0x40000: 'SMARTCARD_REQUIRED',
    0x80000: 'TRUSTED_FOR_DELEGATION',
    0x100000: 'NOT_DELEGATED',
    0x200000: 'USE_DES_KEY_ONLY',
    0x400000: 'DONT_REQ_PREAUTH',
    0x800000: 'PASSWORD_EXPIRED',
    0x1000000: 'TRUSTED_TO_AUTH_FOR_DELEGATION',
    0x04000000: 'PARTIAL_SECRETS_ACCOUNT',
}

# AD timestamp epoch (Jan 1, 1601)
AD_EPOCH_DIFF = 11644473600

# DNS record types
DNS_RECORD_TYPES = ['A', 'AAAA', 'CNAME', 'MX', 'PTR', 'SRV', 'TXT']

# Pagination
DEFAULT_PAGE_SIZE = 25
MAX_PAGE_SIZE = 100
