# Generated by Django 5.1.15 on 2026-02-17 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('username', models.CharField(max_length=150)),
                ('action', models.CharField(db_index=True, max_length=100)),
                ('category', models.CharField(choices=[('authentication', 'Authentication'), ('user_management', 'User Management'), ('group_management', 'Group Management'), ('dns_management', 'DNS Management'), ('gpo', 'GPO'), ('notification', 'Notification'), ('admin', 'Admin')], db_index=True, max_length=50)),
                ('target_dn', models.TextField(blank=True, default='')),
                ('detail', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('success', models.BooleanField(default=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'audit entries',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['category', 'timestamp'], name='audit_category_ts_idx'), models.Index(fields=['user', 'timestamp'], name='audit_user_ts_idx')],
            },
        ),
    ]
