# Generated by Django 5.1.15 on 2026-02-17 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('subject', models.CharField(max_length=255)),
                ('body_html', models.TextField(help_text='HTML body. Use Django template variables.')),
                ('body_text', models.TextField(help_text='Plain text fallback body. Use Django template variables.')),
                ('description', models.TextField(blank=True, help_text='Description of available template variables.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NotificationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backend_type', models.CharField(choices=[('smtp', 'SMTP'), ('ses', 'Amazon SES')], default='smtp', max_length=10)),
                ('smtp_host', models.CharField(blank=True, default='localhost', max_length=255)),
                ('smtp_port', models.PositiveIntegerField(default=25)),
                ('smtp_username', models.CharField(blank=True, default='', max_length=255)),
                ('smtp_password', models.CharField(blank=True, default='', max_length=255)),
                ('smtp_use_tls', models.BooleanField(default=False)),
                ('ses_region', models.CharField(blank=True, default='us-east-1', max_length=50)),
                ('ses_access_key_id', models.CharField(blank=True, default='', max_length=255)),
                ('ses_secret_access_key', models.CharField(blank=True, default='', max_length=255)),
                ('from_email', models.EmailField(default='noreply@example.com', max_length=254)),
                ('warn_days', models.CharField(default='14,7,3,1', help_text='Comma-separated days before password expiry to send warnings.', max_length=50)),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'notification configuration',
                'verbose_name_plural': 'notification configuration',
            },
        ),
        migrations.CreateModel(
            name='SentNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(max_length=254)),
                ('recipient_dn', models.TextField(blank=True, default='')),
                ('subject', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('error_message', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(default=dict)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to='notifications.emailtemplate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
